# Generated by Django 5.0.6 on 2024-05-10 10:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None),
        ),
    ]
