# Generated by Django 5.0.6 on 2024-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientsaccount_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsaccount',
            old_name='name',
            new_name='c_name',
        ),
    ]
