# Generated by Django 5.0.6 on 2024-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_name_clientsaccount_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaccount',
            name='username',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
