# Generated by Django 5.0.6 on 2024-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientsaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaccount',
            name='password',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='clientsaccount',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
