# Generated by Django 5.0.6 on 2024-05-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_tmpregisterstatus_clientsaccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpregisterstatus',
            old_name='remake',
            new_name='remark',
        ),
    ]
