# Generated by Django 5.0.6 on 2024-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_remake_tmpregisterstatus_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaccount',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
