# Generated by Django 5.0.6 on 2024-05-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientsaccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsaccount',
            old_name='c_name',
            new_name='fullname',
        ),
    ]
