# Generated by Django 5.0.6 on 2024-05-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_c_name_clientsaccount_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaccount',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
